import type { EducationVideo, Product } from "@/types";

export const products: Product[] = [
  {
    id: "p1",
    slug: "reactive-blue-19",
    name: "Reactive Blue 19",
    sku: "RB19-25KG",
    cas: "2580-78-1",
    category: "Reactive Dyes",
    division: "inks",
    color: "blue",
    colorHex: "#2563eb",
    purity: 98,
    price: 4550,
    unit: "kg",
    stockKg: 500,
    status: "in-stock",
    grade: "Premium Grade",
    description:
      "High-affinity vinyl sulfone dye offering excellent wash fastness and brilliant blue shades for cellulosic fibers.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDhThTFtl2gNgBos0sdJme3-8no61Do7Jm0lBSAFtk5u0YWJcSBoKGImupl7fwaqBmVHad7N-HmDBc5L3pKFHiwOhnndYMVUIuets6RMPZUAGROdlG7czF-MyKs90UZpgv2sBH6UXgb21R8K6ubaJ64uI6VHI7V7VHrf6pI1rtIUz5n9pLXWLO_fZWPAP6R1cBeLdTHVLW7c5Bg0SCZ8vhCNw3vrom29xtFQ1p0YtldbPm_yhSpBjBv4w",
    packing: "25kg drum",
    featured: true,
  },
  {
    id: "p2",
    slug: "reactive-blue-21",
    name: "Reactive Blue 21",
    sku: "RB21-25KG",
    cas: "12222-73-0",
    category: "Reactive Dyes",
    division: "inks",
    color: "blue",
    colorHex: "#2563eb",
    purity: 98.5,
    price: 4500,
    unit: "kg",
    stockKg: 520,
    status: "in-stock",
    grade: "Industrial Grade",
    description: "Brilliant turquoise reactive dye for cotton and viscose.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuATwMWFSKxhavrfwRA7OFdumiHSKJ9dEShR3bnqFDXXkIMMucQ-wazDvBLCt9uNPDdUFot4nHRJzXXT4CdwCM_KlWb5QI1X7yGEm9Nv57vNLGsipJS_2ZgkvL2PGjr10uA8o3IflN-lFstvnFEXPIkkBW8YlDjecvOxDdtigWC5tZONgDALUVQVxkSl6y-UMjDg8Uf2iK_3rW2Kg9sRgQqtVsSHBIHx3kA9CfWVXYtK_5vdlpceXQi-sQ",
    packing: "25kg drum",
    featured: true,
  },
  {
    id: "p3",
    slug: "acid-red-18",
    name: "Acid Red 18",
    sku: "AR18-25KG",
    cas: "2611-82-7",
    category: "Acid Dyes",
    division: "chemicals",
    color: "red",
    colorHex: "#dc2626",
    purity: 99,
    price: 3250,
    unit: "kg",
    stockKg: 200,
    status: "in-stock",
    grade: "Standard Grade",
    description: "High-purity acid dye for wool, silk and nylon.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBnJM-ddsuOBxgN-GehkU8LJXw1lnmIoSlXuTPA_jBKDpxrIRx_mZRIhNDpWXIZpwLu6CT9dOmqmteiliil-8u7s61WcDqmnzKEXoCU4RtgiLle_B6ejnkcHE5NcwLhMLCNvBk05VuEojIYMeXxCvBUGl3WbclbM3w3r2JCBByBKxi0aeYHch8DWLRdlhXSnPJMyD1ZhwYO2d1_WcME2qNKqpPtCGq_zdzMBnm9tQmEs8oXxOmDbHHWfQ",
    packing: "25kg bag",
  },
  {
    id: "p4",
    slug: "direct-yellow-11",
    name: "Direct Yellow 11",
    sku: "DY11-25KG",
    cas: "1325-37-7",
    category: "Direct Dyes",
    division: "chemicals",
    color: "yellow",
    colorHex: "#eab308",
    purity: 96,
    price: 2800,
    unit: "kg",
    stockKg: 0,
    status: "preorder",
    grade: "Technical Grade",
    description: "Direct yellow for paper and cellulosic dyeing.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBC8hDpEkGAFztriiX7Fck7d-Rpqh82PGNRcP1Gz46KClKiWOKMsIeXuQUbXPJcAZDNZGFasbU3NBRrX6_gVQNTRq9ewSs89kZYFHjZuBWmYKkCHZesCcblgjl9eQFqTeO5Iofpqf4VkrDMYwV8JCQsUemEjZ2aAox15SvHKoAgxuigNb_mg_m8etBeve1wzGj5g8SYf7kUewxLGrD1ZUPQD4fwfA7mA9taFuI-ckzXwJcMIt8LnE0K1g",
    packing: "25kg bag",
  },
  {
    id: "p5",
    slug: "reactive-black-5",
    name: "Reactive Black 5",
    sku: "RB5-50KG",
    cas: "17095-24-8",
    category: "Reactive Dyes",
    division: "inks",
    color: "black",
    colorHex: "#111827",
    purity: 99.5,
    price: 4000,
    unit: "kg",
    stockKg: 1000,
    status: "in-stock",
    grade: "Premium Grade",
    description: "Workhorse vinyl sulfone black with excellent build-up.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBfDyMtXXLjTK5m87FU4XvulrzKht-7eDtBiPbC8tUtKG9kpZcFH5ZBZks5mG0YFf1bRgZnYL3lPxkdFiOR8Lx48USaEuY5kmg2NZ3QKiowJsAZWRQRhz4PcwNexJIuwIIKdt6oDpowTZv2K1rivwEHDnkwO5NUgR5esR2dTLbEyImgttA0zg5zYDLchO2vD9HfeNDgxYbnT3iFrySDNoMzv0WIzUpI9p2Td3HRdOS3mcSgJOjuSJMn2g",
    packing: "50kg bag",
    featured: true,
  },
  {
    id: "p6",
    slug: "acid-green-25",
    name: "Acid Green 25",
    sku: "AG25-25KG",
    cas: "4403-90-1",
    category: "Acid Dyes",
    division: "chemicals",
    color: "green",
    colorHex: "#16a34a",
    purity: 97.5,
    price: 5500,
    unit: "kg",
    stockKg: 150,
    status: "in-stock",
    grade: "Standard Grade",
    description: "Anthraquinone acid green for polyamide and wool.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDfIERxwUD9abkuz-vE5238AoAjBlmNtMdEI5ozt32gs5vutRlihRQc1EaFv8FEBu_tHazWkFD1OlfkDR2mNew5PKw20cA3SxK5oksRY9nrpfqmu2KRVCwJP4DdXEzFImyx9xzsa_-ymG96l1zwAdxUffgH8h7cONvwbtpRSVcbl_R4HWxcx2ltAqPGY1EeH-_4A7lwGh8bg6TkNb84K-JEi6lGG7HpVghjAJas9Tz2JE2-R3cXrUdgHw",
    packing: "25kg drum",
  },
  {
    id: "p7",
    slug: "acid-blue-9",
    name: "Acid Blue 9",
    sku: "AB9-25KG",
    cas: "3844-45-9",
    category: "Acid Dyes",
    division: "chemicals",
    color: "blue",
    colorHex: "#2563eb",
    purity: 97,
    price: 2800,
    unit: "kg",
    stockKg: 180,
    status: "in-stock",
    grade: "Standard Grade",
    description: "Brilliant acid blue for inks, paper and textiles.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuATwMWFSKxhavrfwRA7OFdumiHSKJ9dEShR3bnqFDXXkIMMucQ-wazDvBLCt9uNPDdUFot4nHRJzXXT4CdwCM_KlWb5QI1X7yGEm9Nv57vNLGsipJS_2ZgkvL2PGjr10uA8o3IflN-lFstvnFEXPIkkBW8YlDjecvOxDdtigWC5tZONgDALUVQVxkSl6y-UMjDg8Uf2iK_3rW2Kg9sRgQqtVsSHBIHx3kA9CfWVXYtK_5vdlpceXQi-sQ",
    packing: "25kg drum",
  },
  {
    id: "p8",
    slug: "direct-blue-86",
    name: "Direct Blue 86",
    sku: "DB86-50KG",
    cas: "1330-38-7",
    category: "Direct Dyes",
    division: "chemicals",
    color: "blue",
    colorHex: "#1d4ed8",
    purity: 95,
    price: 1875,
    unit: "kg",
    stockKg: 40,
    status: "low-stock",
    grade: "Technical Grade",
    description: "Phthalocyanine direct blue for paper and cotton.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDfIERxwUD9abkuz-vE5238AoAjBlmNtMdEI5ozt32gs5vutRlihRQc1EaFv8FEBu_tHazWkFD1OlfkDR2mNew5PKw20cA3SxK5oksRY9nrpfqmu2KRVCwJP4DdXEzFImyx9xzsa_-ymG96l1zwAdxUffgH8h7cONvwbtpRSVcbl_R4HWxcx2ltAqPGY1EeH-_4A7lwGh8bg6TkNb84K-JEi6lGG7HpVghjAJas9Tz2JE2-R3cXrUdgHw",
    packing: "50kg bag",
  },
  {
    id: "p9",
    slug: "phthalocyanine-blue-15-3",
    name: "Phthalocyanine Blue 15:3",
    sku: "PB153-25KG",
    cas: "147-14-8",
    category: "Pigments",
    division: "inks",
    color: "blue",
    colorHex: "#1e40af",
    purity: 99,
    price: 5200,
    unit: "kg",
    stockKg: 300,
    status: "in-stock",
    grade: "Premium Grade",
    description: "High-strength copper phthalocyanine for inks and coatings.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBfDyMtXXLjTK5m87FU4XvulrzKht-7eDtBiPbC8tUtKG9kpZcFH5ZBZks5mG0YFf1bRgZnYL3lPxkdFiOR8Lx48USaEuY5kmg2NZ3QKiowJsAZWRQRhz4PcwNexJIuwIIKdt6oDpowTZv2K1rivwEHDnkwO5NUgR5esR2dTLbEyImgttA0zg5zYDLchO2vD9HfeNDgxYbnT3iFrySDNoMzv0WIzUpI9p2Td3HRdOS3mcSgJOjuSJMn2g",
    packing: "25kg drum",
    featured: true,
  },
  {
    id: "p10",
    slug: "super-white-opaque-base",
    name: "Super White Opaque Base",
    sku: "VJ-701",
    category: "Auxiliaries",
    division: "inks",
    color: "white",
    colorHex: "#f8fafc",
    purity: 99,
    price: 850,
    unit: "kg",
    stockKg: 800,
    status: "in-stock",
    grade: "Plastisol Ink",
    description: "High-opacity plastisol base for textile printing, optimized for rapid curing.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDR91E1ifMXLEej9xXzBAiHga5m2DgbJo1mBTjBRzceIMoZfQY2RsT2zctqd2Mmf8LRGxpl7bsPiZ38G30p7KotFqvgi-ZfJX6pnsugOrhQb3eM2klFSEmdFibN0x81ZnZE84v4NGF-XKNZUELM3l7g_hSsY4MOz7lFGjoVMZyTi7fIIy3jm4DP2HB5AkZsqzvNRzRnAR6Dimsahcted5gQm7ajUrajKAAiiU65Sz83uBy6UAO4iv-VFA",
    packing: "5kg / 20kg drums",
    featured: true,
  },
  {
    id: "p11",
    slug: "emulsion-remover-gel",
    name: "Emulsion Remover Gel",
    sku: "EM-220",
    category: "Auxiliaries",
    division: "chemicals",
    color: "yellow",
    colorHex: "#facc15",
    purity: 98,
    price: 1200,
    unit: "L",
    stockKg: 35,
    status: "low-stock",
    grade: "Chemicals",
    description: "Dual-cure emulsion suitable for solvent and plastisol inks. High resolution.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDBXOeHH8SmDkq0Mqjk6JW_VygEoLf7ijp7obn-ZWBCZoy8bpHnJH5Z3Hh07KgavnkMuLkvcww0p7qmKBYRFfTe2Yn7EUQYMyy_vMxd_LTccGSqcIMhU3vWNuuKvVU_pgdFPFMtDUVRsCkEBxiUmWrKSIteiNxcDuQijkJWGKqR10JEWrmL1vdvk89DBUmOe9sK5BdC_sgyD5JzO95ddJEBAAnbD-NJTwS-oFLhOcLZYvcxnqGE8uwDyA",
    packing: "1L / 5L bottles",
    featured: true,
  },
  {
    id: "p12",
    slug: "alu-frame-20x24",
    name: 'Alu Frame 20x24" (156 Mesh)',
    sku: "FR-2024",
    category: "Auxiliaries",
    division: "frames",
    color: "yellow",
    colorHex: "#eab308",
    purity: 100,
    price: 1450,
    unit: "pc",
    stockKg: 0,
    status: "preorder",
    grade: "Frames",
    description: "Pre-stretched aluminum screen printing frame.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBZuWHeY_ngG6R1N_ONQNXh56Vgp8m1seyoxs-Y2HvSq6imPsgZ9_2qv4MK6RLFNxXrfEY9nfV6oRDT188buQXYpq4PH98OY5MDthu_fiIfujy4qVGHqxp6i5ji6gAgDc3nFM4uqyp08-ze5bypoK79Ts5ebkrPCePThd2inZdQ5X0i06-rsNRaitmTJHKMRtRoT_p2lU-T9GpsrVDfqch9yMY4-ifFeY-i3qyBIM91tKj51AeBUeyy2A",
    packing: "Pre-stretched",
  },
  {
    id: "p13",
    slug: "ergo-squeegee-14",
    name: 'Ergo Squeegee 14" (70 Durometer)',
    sku: "SQ-80",
    category: "Auxiliaries",
    division: "squeegees",
    color: "green",
    colorHex: "#16a34a",
    purity: 100,
    price: 450,
    unit: "m",
    stockKg: 120,
    status: "in-stock",
    grade: "Tools",
    description: "Solvent-resistant squeegee blade with sharp edge profile for fine details.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDU4xuwdieBqfQ42O2W2j5GR7GgrYkJrlC4S-zGN7je563GsotKfP2FznhXbFmSGYPNDjaeGsPdB-y1kV7mKfMKfH6vvTDaavdUaQKWN4giJ9b5807iGaQq0-fcujqqz-GMAbcP_-UfEyJZQ88K0I7e_DeiKbvoZeA7CySENfrVxW8BPAqp6yFRpjPNbcZmDppCN5jtPchKYcUlsIjY93THpuZgybtEl2TrOViWwHxZ3qNpZUoQDgLNzA",
    packing: "Single unit",
    featured: true,
  },
  {
    id: "p14",
    slug: "sodium-hydrosulfite",
    name: "Sodium Hydrosulfite (Hydros)",
    sku: "SHS-90-50KG",
    category: "Auxiliaries",
    division: "chemicals",
    color: "white",
    colorHex: "#e5e7eb",
    purity: 90,
    price: 2250,
    unit: "kg",
    stockKg: 400,
    status: "in-stock",
    grade: "Industrial Grade",
    description: "Reducing agent for vat dyeing and discharge printing.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBnJM-ddsuOBxgN-GehkU8LJXw1lnmIoSlXuTPA_jBKDpxrIRx_mZRIhNDpWXIZpwLu6CT9dOmqmteiliil-8u7s61WcDqmnzKEXoCU4RtgiLle_B6ejnkcHE5NcwLhMLCNvBk05VuEojIYMeXxCvBUGl3WbclbM3w3r2JCBByBKxi0aeYHch8DWLRdlhXSnPJMyD1ZhwYO2d1_WcME2qNKqpPtCGq_zdzMBnm9tQmEs8oXxOmDbHHWfQ",
    packing: "50kg drum",
  },
  {
    id: "p15",
    slug: "reactive-red-195",
    name: "Reactive Red 195 (M-Type)",
    sku: "RR195-25KG",
    cas: "93050-79-4",
    category: "Reactive Dyes",
    division: "inks",
    color: "red",
    colorHex: "#dc2626",
    purity: 98,
    price: 12850,
    unit: "kg",
    stockKg: 220,
    status: "in-stock",
    grade: "Premium Grade",
    description: "High-exhaustion bifunctional reactive red for cotton.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBC8hDpEkGAFztriiX7Fck7d-Rpqh82PGNRcP1Gz46KClKiWOKMsIeXuQUbXPJcAZDNZGFasbU3NBRrX6_gVQNTRq9ewSs89kZYFHjZuBWmYKkCHZesCcblgjl9eQFqTeO5Iofpqf4VkrDMYwV8JCQsUemEjZ2aAox15SvHKoAgxuigNb_mg_m8etBeve1wzGj5g8SYf7kUewxLGrD1ZUPQD4fwfA7mA9taFuI-ckzXwJcMIt8LnE0K1g",
    packing: "25kg bag",
  },
];

export const videos: EducationVideo[] = [
  {
    id: "v1",
    slug: "cmyk-separation-mastery",
    title: "CMYK Separation Mastery for Plastisol Inks",
    description:
      "Learn the precise techniques for separating CMYK artwork specifically for plastisol inks. We'll cover dot angles, LPI considerations for different mesh counts, and how to calibrate your exposure unit for optimal halftone retention.",
    duration: "34:20",
    durationSeconds: 2060,
    views: 2140,
    tier: "Advanced",
    category: "Inks",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuActig2vfayEnfpyNQ9JKO6HPsj5OrTn6pEn1_enpnE9tYcOttdC7rC2nCmA0hWmGav2SyO_07Pg2f9z-BTVn6DsmoUXrc7OjcnvZcxSBiersnBGv1wLSvnAZwOisNMunwfxP2YJ66sxOm90_yy9VNDfc7u9tfagVO0PUy4H6xJGfycEJBm9JL6mv_A7fgforRqe2nwWE5DllMz0EGMCK5_0t6wUX4ZXFmRMGkTredyqhgj--TaYljjXA",
    mesh: "230 - 305 tpi",
    inkType: "Plastisol (Process)",
  },
  {
    id: "v2",
    slug: "emulsion-coating-basics",
    title: "Fundamentals of Emulsion Coating",
    description:
      "Learn the critical steps to achieving an even, consistent emulsion layer for sharp, professional stencil creation in industrial screen printing applications.",
    duration: "5:12",
    durationSeconds: 312,
    views: 850,
    tier: "Beginner",
    category: "Guide",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDvuubbicQeIEGuGqCvwhdtElLKfz-1HDGTltvz43LX-H8ie-uo1iLEavu9qSzb4q-XXK3LWLXP3U54AmHpTGv3ebf7khu6nC3C7WXd_ZbcTkYBbhsyVdn4EoijONfoXDPqCjhCOKdFVbTpdJk_pnVIsWqiApfKXO5tCfiLkTlzE760DVG0LMSB0Bmbju9HgIrIPLXFkRVbTdKyTuReOW0dEjYWL-TjVrdPeHBXZ46oSYBcmMfdhOjTXdeA",
  },
  {
    id: "v3",
    slug: "plastisol-curing-tech",
    title: "Proper Plastisol Curing Tech",
    description: "Technical bulletin on achieving perfect coverage on dark garments.",
    duration: "3:45",
    durationSeconds: 225,
    views: 1200,
    tier: "Tutorial",
    category: "Inks",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB2OCcKD6BX1XFbEwJN4hOICLvnXfn8at2wLOLwqoinnDWroSUPWlMqoQTMAynP40WG5i_LaI7u1CTnSD0_Y-pI_rQd3RcAvsIGae6_ynYiQ2bLgr1zldyElil7y71mQZCS4vku8OHe1scDqlAJ-p_eIq7zxm1HP5z1Bh31rZny76L7anoU5L2IKoFxdSHb3zyOYp6mkG6aemhY_ZMLfFqXFuwQmWenAduC32uB_oLz2qO3MpvxWka2Gw",
  },
  {
    id: "v4",
    slug: "color-mixing-viscosity",
    title: "Advanced Color Mixing & Viscosity Control",
    description:
      "Master the art of modifying ink viscosity for high-mesh counts without compromising opacity.",
    duration: "12:10",
    durationSeconds: 730,
    views: 640,
    tier: "Advanced",
    category: "Inks",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBjR5qKnNTICwFeND8GbVQ0L-SZjp81j8qKn8Z4ImMgOVZ0KQtS7g6n2rXprjtxWEGBJxA7OxB3aop91AVf1-BYOB4oBDAo9TgY3aw11r0DxhN0beBLCcogBaVySp2t0VKoHit8cmW7B0sm5yISNDqwoBMZQ7zFMMhGUAnFp8NLVMBYrwb_QpInGB2d7FJ_q8chtGj2d8celxecrTImofiw2uVb-Ljtff8TBv4BwEEAx5rqypaeb-I_dA",
  },
  {
    id: "v5",
    slug: "workspace-setup-safety",
    title: "Workspace Setup & Safety",
    description: "Lab safety, SDS handling and workstation layout for dye houses.",
    duration: "08:15",
    durationSeconds: 495,
    views: 3100,
    tier: "Beginner",
    category: "Guide",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCoRMZZxStiOH999pMXvwKdKIbkNnDGj9d5YoLlqFw4jZfBBlrP14gaxwxLm0xiMEFkuStE0yj8T1d5xVIbnAz66mYT2ThI2w0pL3J-aE_Tnsb5VrwMduLmIoiTCLtWBHgBVDw6AqkeR2P6Rd9zLcHHszwHYg9OnkQaDzXQBZ3WJx_AhSpbuHftTFDcuVCSIL4xKwgV0t6BUxKzRyotleR4yM_nRViGa6_r1GybbuA9VNd0s5_3uX_yxw",
  },
  {
    id: "v6",
    slug: "registration-multicolor",
    title: "Registration Techniques for Multi-Color",
    description: "Aligning screens for tight multi-color industrial prints.",
    duration: "22:10",
    durationSeconds: 1330,
    views: 980,
    tier: "Advanced",
    category: "Guide",
    thumbnail:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuALNBhQcQKq2ukpTb2OmEoVs6JbGbWgjqR6b7NzStR1aVH4EXUZpYnOkUAKDFEJ3-SvNL7gaANTl13PzO_NsgZ8kR_kXFVELWdMeetptmrokq42xHF-M4H36OGvItHnlcZ8yL9H_IRIm_0hiHkc9iyk6P4VRA79PpMU4kolrxUodxtUNtVJ0qNrnfGhPV42wgp9GCUoHekAC3BndOQIUHox2SAPfpiT5zln7WlfhtaNvuhs-zlaUGlyw",
  },
];

export function getProduct(slugOrId: string) {
  return products.find((p) => p.slug === slugOrId || p.id === slugOrId);
}

export function getVideo(slugOrId: string) {
  return videos.find((v) => v.slug === slugOrId || v.id === slugOrId);
}
